"""
Per-device tokens.

The hub binds to the Tailscale interface, so the network is already private;
tokens are the second layer that stops a compromised device on the tailnet
from impersonating another. Tokens live in hub/secrets.yaml (gitignored) and
are generated by scripts/new_device.py.
"""
from __future__ import annotations

import hmac
import logging
from pathlib import Path
from typing import Any

import yaml

log = logging.getLogger("jarvis.auth")


class Auth:
    def __init__(self, secrets_path: Path) -> None:
        self.path = secrets_path
        self._devices: dict[str, dict[str, Any]] = {}
        self.reload()

    def reload(self) -> None:
        if not self.path.exists():
            log.warning("no secrets file at %s -- every connection will be refused. "
                        "Run: python scripts/new_device.py <name>", self.path)
            self._devices = {}
            return
        data = yaml.safe_load(self.path.read_text(encoding="utf-8")) or {}
        self._devices = data.get("devices", {}) or {}
        log.info("loaded %d device tokens", len(self._devices))

    def check(self, device: str, token: str) -> bool:
        entry = self._devices.get(device)
        if not entry or not token:
            log.warning("auth rejected: unknown device %r", device)
            return False
        # compare_digest: constant time, so a wrong token leaks no timing signal.
        if not hmac.compare_digest(str(entry.get("token", "")), token):
            log.warning("auth rejected: bad token for %r", device)
            return False
        return True

    def meta(self, device: str) -> dict[str, Any]:
        return self._devices.get(device, {})

    def aliases(self, device: str) -> list[str]:
        """Spoken names for this machine, e.g. ['bedroom laptop', 'the small one']."""
        return list(self._devices.get(device, {}).get("aliases", []) or [])
